Do 2nd spring-boot-practise
artificialLeo/mate-bs pull request #15
Opened 2023-12-13 17:35 UTC by artificialLeo

2023-12-14 11:43 UTC, Sanderfuck requested changes

2023-12-14 11:43 UTC, Sanderfuck commented on store/src/main/java/com/book/store/controller/ShoppingCartController.java
> +            @ApiResponse(responseCode = "400", description = "Invalid request parameters")
For what you need this?

2023-12-14 11:43 UTC, Sanderfuck commented on store/src/main/java/com/book/store/controller/ShoppingCartController.java
> +            @ApiResponse(responseCode = "400", description = "Invalid request parameters")
Is it make any sense?

2023-12-14 11:43 UTC, Sanderfuck commented on store/src/main/java/com/book/store/service/impl/ShoppingCartServiceImpl.java
> +
```suggestion
```

2023-12-14 11:43 UTC, Sanderfuck commented on store/src/main/java/com/book/store/controller/ShoppingCartController.java
> +        }
Why you make validation here and where your dto?

2023-12-14 11:43 UTC, Sanderfuck commented on store/src/main/java/com/book/store/controller/ShoppingCartController.java
> +        }
You wrap every method by try catch, is it important use it here?

2023-12-15 14:06 UTC, kerrrusha approved these changes

2023-12-16 13:01 UTC, closed without merging