Do 3 part of SB practice
artificialLeo/mate-bs pull request #17
Opened 2023-12-16 13:01 UTC by artificialLeo

2023-12-16 16:09 UTC, sokimaaa commented on store/src/main/java/com/book/store/controller/OrderController.java
> +    }
use static method to create. 
```suggestion
        return ResponseEntity.created(...); // builder pattern here
    }
```

2023-12-16 16:10 UTC, sokimaaa commented on store/src/main/java/com/book/store/controller/OrderController.java
> +        return new ResponseEntity<>(orderHistory, HttpStatus.OK);
Prefer using static method for creation
```suggestion
        return ResponseEntity.ok(orderHistory);
```

2023-12-16 16:12 UTC, sokimaaa commented on store/src/main/java/com/book/store/model/Order.java
> +    private String shippingAddress;
There are validation annotations, you need to add database constraints, e.g. Using @Column
```suggestion
    private User user;

    @Enumerated(EnumType.STRING)
    private Status status;

    private BigDecimal total;

    @NotNull
    private LocalDateTime orderDate;


    private String shippingAddress;
```

2023-12-16 16:14 UTC, sokimaaa commented on store/src/main/java/com/book/store/controller/OrderController.java
> +    public ResponseEntity<OrderDto> placeOrder(@Valid @RequestBody OrderDto orderDto) {
Take OrderDto - return OrderDto : weird decision
You are using @Valid for OrderDto, but it has no rule for validation. 
```suggestion
    public ResponseEntity<OrderDto> placeOrder(@Valid @RequestBody OrderDto orderDto) {
```

2023-12-16 16:15 UTC, sokimaaa commented on store/src/main/java/com/book/store/dto/OrderDto.java
> +    private Long id;
any validation rules, but uses @Valid to trigger them

2023-12-16 16:15 UTC, sokimaaa commented on store/src/main/java/com/book/store/model/OrderItem.java
> +    private BigDecimal price;
Remove validation annotation, you need to add database constraints

2023-12-16 16:16 UTC, sokimaaa commented on store/src/main/java/com/book/store/model/Status.java
> +    CANCELED
Check what is @Enumerated and why we are using it

2023-12-16 16:17 UTC, sokimaaa commented on store/src/main/java/com/book/store/service/OrderService.java
> +    Page<OrderDto> getUserOrderHistory(Pageable pageable);
```suggestion
    List<OrderDto> getUserOrderHistory(Pageable pageable);
```

2023-12-16 16:18 UTC, sokimaaa commented on store/src/main/java/com/book/store/service/impl/OrderItemServiceImpl.java
> +                .collect(Collectors.toSet());
inline code
```suggestion
        Set<OrderItem> orderItems = orderItemRepository.findAllByOrderId(orderId);
        return orderItems.stream()
                .map(orderItemMapper::mapToOrderItemDto)
                .collect(Collectors.toSet());
```

2023-12-16 16:18 UTC, sokimaaa commented on store/src/main/java/com/book/store/service/impl/OrderItemServiceImpl.java
> +        return orderItemMapper.mapToOrderItemDto(orderItem);
inline
```suggestion
        OrderItem orderItem = orderItemRepository
                .findByIdAndOrderId(itemId, orderId)
                .orElseThrow(()
                        -> new EntityNotFoundException("OrderItem not found with id: " + itemId));
        return orderItemMapper.mapToOrderItemDto(orderItem);
```

2023-12-16 16:18 UTC, sokimaaa commented on store/src/main/java/com/book/store/service/impl/OrderServiceImpl.java
> +        return userOrders.map(orderMapper::mapToOrderDto);
inline
```suggestion
        Page<Order> userOrders = orderRepository.findAll(pageable);
        return userOrders.map(orderMapper::mapToOrderDto);
```

2023-12-17 12:35 UTC, Sanderfuck requested changes

2023-12-17 12:35 UTC, Sanderfuck commented on store/src/main/java/com/book/store/dto/OrderDto.java
> +    @NotNull
```suggestion
    @NotNull
    @Min(0)
```

2023-12-17 12:35 UTC, Sanderfuck commented on store/src/main/java/com/book/store/dto/OrderDto.java
> +    @NotNull
Add more validation of fields

2023-12-17 12:35 UTC, Sanderfuck commented on store/src/main/java/com/book/store/model/OrderItem.java
> +    @ManyToOne
Is it Many to One?

2023-12-18 10:53 UTC, Rommelua requested changes
![image](https://github.com/artificialLeo/mate-bs/assets/20326858/92f5589b-248c-4e61-b845-12c309a4795b)

2023-12-19 15:41 UTC, kerrrusha approved these changes

2023-12-20 18:47 UTC, merged