dto validation done
artificialLeo/mate-bs pull request #7
Opened 2023-11-21 18:44 UTC by artificialLeo

2023-11-21 19:08 UTC, Rommelua requested changes
I can't believe that this validation works. Have you tested it?

2023-11-22 19:59 UTC, kerrrusha requested changes

2023-11-22 19:59 UTC, kerrrusha commented on store/src/main/java/com/book/store/dto/BookDto.java
> +    @DecimalMin(value = "0.01", message = "Price must be greater than 0")
```suggestion
    @DecimalMin(value = "0.0", inclusive = false, message = "Price must be greater than 0")
```

2023-11-22 19:59 UTC, kerrrusha commented on store/src/main/java/com/book/store/dto/BookDto.java
>      private String isbn;
```suggestion
    @Size(min = 1, max = 13, message = "ISBN must be between 1 and 13 characters.")
    private String isbn;
```

2023-11-22 19:59 UTC, kerrrusha commented on store/src/main/java/com/book/store/dto/BookDto.java
>      private String author;
```suggestion
    @Size(min = 1, max = 255, message = "Author must be between 1 and 255 characters.")
    private String author;
```

2023-11-22 19:59 UTC, kerrrusha commented on store/src/main/java/com/book/store/dto/BookDto.java
>      private String title;
```suggestion
    @Size(min = 1, max = 255, message = "Title must be between 1 and 255 characters.")
    private String title;
```

2023-11-22 19:59 UTC, kerrrusha commented on store/src/main/java/com/book/store/dto/BookDto.java
>      private String description;
```suggestion
    @Size(max = 2000, message = "Description can't be longer than 2000 characters.")
    private String description;
```

2023-11-22 19:59 UTC, kerrrusha commented on store/src/main/java/com/book/store/dto/BookRequestDto.java
> +    @NotBlank(message = "Title is required")
same in this class

2023-11-23 19:13 UTC, sokimaaa commented on store/src/main/java/com/book/store/dto/BookDto.java
> +    @NotBlank(message = "Title is required")
Have you used BookDto validations? I didnt see

Code that are not in use should be removed

2023-11-24 19:05 UTC, merged